name: Build and deploy

on: [push]

jobs:
  build:
    name: Build binary
    runs-on: ubuntu-latest
    steps:
      - name: Check out files from GitHub
        uses: actions/checkout@v4.1.0
      # https://github.com/actions/setup-go
      - name: Setting up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
      - name: Build binary
        run: go build -o dbot main.go

      # TODO: Continue updating the binary on EC2
      # - name: Upload to EC2
      #   env:
      #     AWS_KEY: ${{ secrets.aws_key }}
      #     EC2_IP: ${{ secrets.ec2_ip }}
      #   run: |
      #     echo "$AWS_KEY" > .ssh/aws_key;
      #     scp 
      #     ssh -i .ssh/aws_key "$EC2_IP"
