name: Build and deploy

on: [push]

jobs:
  build:
    name: Build binary
    runs-on: ubuntu-latest
    steps:
      # - name: Check known hosts
      #   run: |
      #     ls "$HOME/.ssh"
      #     echo "$HOME/.ssh/known_hosts"
      #     exit 1
      - name: Check out files from GitHub
        uses: actions/checkout@v4.1.0
      # https://github.com/actions/setup-go
      - name: Setting up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
        continue-on-error: true
      - name: Build binary
        run: go build -o dbot main.go
      - name: Upload to EC2
        env:
          AWS_KEY: ${{ secrets.AWS_KEY }}
          ENV: ${{ secrets.ENV }}
          EC2_INSTANCE: ${{ secrets.EC2_INSTANCE }}
        run: |
          mkdir "$HOME/.ssh";
          echo "$AWS_KEY" > "$HOME/.ssh/aws_key";
          chmod 400 "$HOME/.ssh/aws_key";
          echo "ec2-51-20-63-178.eu-north-1.compute.amazonaws.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPizi++gnfLgkIW3qHSViUeaUXTgtk9RVzwpzPQUXMU/7CF3+i/08WHdKhWfXlSyrAt1u5oGFGxsv2Wgoyvc3+Y=" > "$HOME/.ssh/known_hosts";
          echo "$ENV" > .env;
          scp -i "$HOME/.ssh/aws_key" .env "$EC2_INSTANCE";
          scp -i "$HOME/.ssh/aws_key" dbot "$EC2_INSTANCE";
          ssh -i "$HOME/.ssh/aws_key" "$EC2_INSTANCE" sudo systemctl restart dbot-signup;
          ssh -i "$HOME/.ssh/aws_key" "$EC2_INSTANCE" sudo systemctl restart dbot-league;
