name: Build and deploy

on: [push]

jobs:
  build:
    name: Build binary
    runs-on: ubuntu-latest
    steps:
      - name: Check out files from GitHub
        uses: actions/checkout@v4.1.0
      # https://github.com/actions/setup-go
      - name: Setting up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
      - name: Build binary
        run: go build -o dbot main.go
      - name: Upload to EC2
        env:
          AWS_KEY: ${{ secrets.AWS_KEY }}
          ENV: ${{ secrets.ENV }}
          EC2_INSTANCE: ${{ secrets.EC2_INSTANCE }}
        run: |
          echo "$AWS_KEY" > .ssh/aws_key;
          echo "$ENV" > .env
          scp -i .ssh/aws_key .env "$EC2_INSTANCE"
          scp -i .ssh/aws_key dbot "$EC2_INSTANCE"
          ssh -i .ssh/aws_key "$EC2_INSTANCE" sudo systemctl restart dbot-signup
          ssh -i .ssh/aws_key "$EC2_INSTANCE" sudo systemctl restart dbot-league
